### ISSUE TITLE
Following installation instructions leads to failure

### ISSUE THREAD

**Issue by mietek** [lurk-lab/lurk#440]
Following the installation instructions given in the [Lurk User Manual](https://docs.argument.xyz/02-setup.html) leads to a failed build in a fresh Rust 1.93.1 environment.
```
% cargo install --path .
  Installing lurk v0.5.0 (/Users/mietek/Repositories/lurk)
    Updating git repository `https://github.com/lurk-lab/p3.git`
    Updating crates.io index
    Updating git repository `https://github.com/argumentcomputer/ascent.git`
warning: patch `p3-poseidon2 v0.2.1-succinct (https://github.com/lurk-lab/p3.git?branch=sp1-v4#f151ebd0)` was not used in the crate graph
help: Check that the patched package version and available features are compatible
      with the dependency requirements. If the patch has a different version from
      what is locked in the Cargo.lock file, run `cargo update` to use the new
      version. This may also occur with an optional dependency that is not enabled.
     Locking 640 packages to latest compatible versions
      Adding ...
  Downloaded ...
  Downloaded alloy-serde v0.11.1
  Downloaded ...
  Downloaded serde v1.0.228
  Downloaded ...
  Downloaded alloy-consensus v0.11.1
  Downloaded 553 crates (42.6MiB) in 2.39s (largest was `alloy-consensus` at 7.6MiB)
   Compiling ...
   Compiling serde v1.0.228
   Compiling ...
   Compiling alloy-serde v0.11.1
   Compiling ...
   Compiling alloy-consensus v0.11.1
error[E0433]: failed to resolve: could not find `__private` in `serde`
   --> /Users/mietek/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-consensus-0.11.1/src/transaction/envelope.rs:686:34
    |
686 |             let content = serde::__private::de::Content::deserialize(deserializer)?;
    |                                  ^^^^^^^^^ could not find `__private` in `serde`

error[E0433]: failed to resolve: could not find `__private` in `serde`
   --> /Users/mietek/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-consensus-0.11.1/src/transaction/envelope.rs:688:24
    |
688 |                 serde::__private::de::ContentRefDeserializer::<D::Error>::new(&content);
    |                        ^^^^^^^^^ could not find `__private` in `serde`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `alloy-consensus` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lurk v0.5.0 (/Users/mietek/Repositories/lurk)`, intermediate artifacts can be found at `/Users/mietek/Repositories/lurk/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
The build fails because `serde v1.0.228` is getting pulled in, even though `serde v1.0.219` is specified in the lockfile. This happens because `cargo install` ignores the lockfile by default.
